pip install alive_progress
pip install tqdm
pip install requests
pip install py7zr
pip install logging
pip install datetime
pip install shutil
pip install hashlib
pip install platform
pip install zipfile
